name: Test On Review

on:
  workflow_call:
    inputs: {}

permissions:
  contents: read
  pull-requests: write
  checks: write
  statuses: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}-ON-REVIEW
  cancel-in-progress: true

jobs:
  CheckRequiredReviews:
    name: Check Required Reviews
    runs-on: ubuntu-latest
    steps:
      - name: Check Required Reviews
        uses: nickjmoss/.github/.github/actions/on-review/action.yaml@main
